
mahsulot = {
    '2 Лаваша с говядиной и сыром' : "2 Лаваша с говядиной и сыром\nNarxi: 59 000 so'm",
    "2 Триндвича с говядиной" : "2 Триндвича с говядиной\nNarxi: 59 000 so'm",
    "2 Салата Греческих" : "2 Салата Греческих\nNarxi: 43 000 so'm",
    "2 Салата Цезарь" : "2 Салата Цезарь\nNarxi: 45 000 so'm",
    "2 Картошки фри" : "2 Картошки фри\nNarxi: 25 000 so'm",
    'Fit-Plus 2' : "Eng mazali va to'yimli past kaloriyali Sezar salati , shakarsiz Dena sharbati 0,33l. Kaloriyalarini kuzatuvchilar uchun ajoyib tanlov!\nNarxi: 30 000 so'm",
    "Fit-Plus 3" : "Eng mazali va to'yimli past kaloriyali Grecheskiy salati , shakarsiz Dena sharbati 0,33l. Kaloriyalarini kuzatuvchilar uchun ajoyib tanlov!\nNarxi: 30 000 so'm",
    "Fri Plus" : "Tillarang kartoshka-fri portsiyasi va bir stakan 'Pepsi'\nNarxi: 19 000 so'm",
    "Fri Plus 7up" : "Tillarang kartoshka-fri portsiyasi va bir stakan '7up'\nNarxi: 19 000 so'm",
    "Fit-Plus 1" : "Grillda pishirilgan yumshoq tovuq go'shti, 'Aysberg' salati, pishib yetilgan pomidor va bodring bo'laklari, yumshoq 'Fetaksa' pishlog'i, och yashil rangli Fitter lavashidagi yengil qaymoqli Eko sousi. Qo'shimcha ravishda shakarsiz past kaloriyali Dena 0,33l sharbati\nNarxi: 33 000 so'm",
    "Double Set 2" : "Double Set seriyasi - ikki kishi uchun hamyonbop yechim! Double Set №2 tarkibiga kiradi: mol go'shtli shaurma va qarsildoq kartoshka fri mini ikkitalik porsiyasi hamda albatta, 2 stakan «Pepsi».\nNarxi: 80 000 so'm",
    "Double Set 1" : "Double Set seriyasi - ikki kishi uchun hamyonbop yechim! Double Set №1 tarkibiga kiradi: mol go'shtli lavash va qarsildoq kartoshka smayliklarining ikkitalik porsiyasi hamda albatta, 2 stakan «Pepsi».\nNarxi: 89 000 so'm",
    "Oilaviy Set 1" : "Oilaviy Set - oilaning barcha a'zolari uchun hamyonbop zavqlanish imkoni! Oilaviy Set №1 tarkibiga quyidagilar kiradi: 2 (ikkita) standart mo'l go'shtli lavash + 2 (ikkita) xot dog kids, 2 (ikki) porsiya qarsildoq kartoshka fri mini, bolajonlar va kattalarni shodlantiruvchi ikki (2) porsiya quvnoq kartoshka smayliklari. To'plam tarkibiga 4 stakan Pepsi kiradi.\nNarxi: 135 000 so'm",
    "Mol go'shtidan qalampir lavash" : "Shirali gril mol go'shti bo'lakchalari, yetilib pishgan pomidor bo'laklari, tillarang chipslar, qizg'ish red-lavashdagi yangi piyoz bilan achchiq Qalampir tomatli sousi\nNarxi: 32 000 so'm",
    "Tovuq go'shtidan qalampir lavash" : "Yengil achchiq ta'mli tovuq go'shti-gril, yetilib pishgan pomidor bo'lakchalari, tillarang chipslar, 'Chedder' pishlog'i, qizg'ish red-lavashdagi yangi piyoz bilan achchiq Qalampir tomatli sousi\nNarxi: 30 000 so'm",
    "Tovuq go`shtidan lavash" : "Tovuq go`shtidan lavash\nNarxi: 30 000 so'm",
    "Tovuq go`shtidan sab" : "Tovuq go'shti-gril, yangi, qizil piyoz halqasi, cho'zinchoq bo'rsildoq bulochkadagi tutunli 'Barbekyu' sousi bilan\nNarxi: 18 000 so'm",
    "Mol go`shtidan pishloqli sab" : "Shirali gril mol go'shti, yangi, qizil piyoz halqasi, cho'zinchoq bo'rsildoq bulochkadagi shirin iforga ega 'Chedder' pishlog'i bo'lagi va tutunli 'Barbekyu' sousi bilan\nNarxi: 22 000 so'm",
    "Tovuq go`shtidan pishloqli sab" : "Tovuq go'shti-gril, yangi, qizil piyoz halqasi, cho'zinchoq bo'rsildoq bulochkadagi shirin iforga ega 'Chedder' pishlog'i bo'lagi va tutunli 'Barbekyu' sousi bilan\nNarxi: 20 000 so'm",
    "Naggetslar, 4 dona" : "shtahaochar qarsildoq qobiqdagi tovuq  filesi bo'lakchalari. Porsiya - 4 dona.\nNarxi: 10 000 so'm",
    "Naggetslar, 8 dona" : "Ishtahaochar qarsildoq qobiqdagi tovuq  filesi bo'lakchalari.Porsiya - 8 dona.\nNarxi: 18 000 so'm",
    "Kartoshka Fri Mini" : "Mazali, o'simlik yog'li frityurda qovurilgan va yengil tuzlangan kartoshka qalamchalari. Sevimli sous bilan birgalikda tanovul qilinsa - idealdir!\nNarxi: 10 000 so'm",
    "Jaydari kartoshka" : "Xushbo'y ziravorlar bilan o'simlik yog'li frityurda qovurilgan, ishtahaochar va mazali yirik kartoshka bo'laklari. Sevimli sous bilan tatib ko'ring!\nNarxi: 16 000 so'm",
    "Hot-Dog-Dabl" : "Ikkita ishtahaochar sosiska, yangi pomidor va marinadlangan karsildoq bodring bo'lakchalari, 'Aysberg' salat bargi, mayin kunjutli bagetdagi maxsus qaymoqli sous ostida yangi pomidor bo'laklari va 'Chedder' pishloq bo'lagi bilan\nNarxi: 22 000 so'm",
    "Hot-Dog Mini" : "Kurka go'shtli Kanada sosiskalari, klassik uzun bulochkada qarsildoq piyozli fri va tomatli-xantalli sous\nNarxi: 9 000 so'm",
    "Bolalar uchun Hot-Dog" : "Kurka go'shtli Kanada sosiskalari, qarsildoq piyozli fri, yumshoq bulochkada pishloqli sous\nNarxi: 9 000 so'm",
    'Fitter' : "Mayin tovuq go'shti-gril, 'Aysberg' salat bargi, yangi, yetilib pishgan pomidor va barra bodring bo'lakchalari, 'Fetaksa' yumshoq pishlog'i, mayin-yashil rangli Fitter lavashdagi yengil qaymoqli Eko sous\nNarxi: 29 000 so'm",
    "Trindwich mol go'shtidan" : "Yumshoq pishloqli tortilyadagi maxsus  sous ostida pishloq va pomidor bilan  mayin mol go'shti-grill!\nNarxi: 35 000 so'm",
    "Trindwich tovuq go'shtidan" : "Yumshoq tortilyadagi xushbo'y sous ostida pishloq va pomidorlar bilan mayin tovuq go'shti-grill!\nNarxi: 33 000 so'm",
    "Mol go'shtidan shaurma" : "Mol go'shtidan shaurma\nNarxi: 30 000 so'm",
    "Tovuq go'shtidan shaurma" : "Tovuq go'shtidan shaurma\nNarxi: 27 000 so'm",
    "Tovuq go'shtidan qalampir shaurma" : "Tovuq go'shtidan qalampir shaurma\nNarxi: 27 000 so'm",
    "Mol go'shtidan qalampir shaurma" : "Mol go'shtidan qalampir shaurma\nNarxi: 30 000 so'm",
    "Gamburger" : "Yumshoq va dumaloq bulochkadagi xushboy Grill sousi ostida mol go'shtidan shirali kotlet, yangi yetilib pishgan pomidor va marinadlangan bodringning dumaloq bo'lakchalari, qizil piyoz halqasi va 'Aysberg' salati bargi\nNarxi: 24 000 so'm",
    "Kids-Kvadrich" : "Kvadrich – tillarang qobiqdagi tovuqli kotlet-grill, qaymoqli mayin sousli qovurilgan tuxum bilan qarsildoq chiabattadagi original kvadrat sendvich.\nNarxi: 16 000 so'm",
    "Dablburger" : "Yumshoq va dumaloq bulochkadagi xushboy Grill sousi ostida mol go'shtidan ikkita shirali kotlet, yangi yetilib pishgan pomidor va marinadlangan bodringning dumaloq bo'lakchalari, qizil piyoz halqasi, 'Aysberg' salati bargi\nNarxi: 37 000 so'm",
    "Dablchizburger" : "Yumshoq va dumaloq bulochkadagi xushboy Grill sousi ostida 1 mol go'shtidan ikkita shirali kotlet, ikki bo'lak 'Chedder' pishlog'i, yangi yetilib pishgan pomidor va marinadlangan bodringning dumaloq bo'lakchalari, qizil piyoz halqasi, 'Aysberg' salati bargi\nNarxi: 41 000 so'm",
    "Chizburger" : "Yumshoq va dumaloq bulochkadagi xushboy Grill sousi ostida mol go'shtidan shirali kotlet, 'Chedder' pishlog'i bo'lagi, yangi yetilib pishgan pomidor va marinadlangan bodringning dumaloq bo'lakchalari, qizil piyoz halqasi, 'Aysberg' salati bargi\nNarxi: 26 000 so'm",
    "Mol go`shtidan sab" : "Shirali gril mol go'shti, yangi, qizil piyoz halqasi, cho'zinchoq, bo'rsildoq bulochkadagi tutunli 'barbekyu' sousi bilan\nNarxi: 20 000 so'm",
    "Kartoshka Fri" : "Mazali, o'simlik yog'li frityurda qovurilgan va yengil tuzlangan kartoshka qalamchalari. Sevimli sous bilan birgalikda tanovul qilinsa - idealdir!\nNarxi: 15 000 so'm",
    "Hot-Dog" : "Ishtahaochar sosiska, yangi pomidor va marinadlangan karsildoq bodring bo'lakchalari, mayin kunjutli bagetdagi maxsus qaymoqli sous ostida 'Aysberg' salat bargi\nNarxi: 15 000 so'm",
    "Smayliki" : "Qizg’ich kartoshka kulgichlari - kun davomida tabassum!\nNarxi: 15 000 so'm",
    "Grecheskiy salat" : "Yangi pomidor va bodring, zaytun, yumshoq  'Fetaksa' pishlog'i hushboy ziravorli yog'li  sous bilan. Sevimli klassika yangi  ko'rinishda!\nNarxi: 24 000 so'm",
    "Non" : "Shirin iforga ega yangi non\nNarxi: 4 000 so'm",
    "Guruch" : "Oq guruch va arpaning aralashmasidan mazali va foydali garnir\nNarxi: 8 000 so'm",
    "Tovuq go'shtidan donar" : "Kombinatsiyali idishda tovuq go'shti-gril bo'lakchalari, tillarang kartoshka-fri, miks-guruch, tabiiy, o'zimizda tayyorlangan salat, maxsus sous va shirin iforga ega kulcha non\nNarxi: 45 000 so'm",
    "Donar-box mol go'shtli" : "Yangi teriyaki sousining g'ayrioddiy mazali kombinatsiyasi, mol grill go’shti, qarsillama kartoshka fri bilan guruch donalari. Qulay ixcham, ammo toyimli mahsulot!\nNarxi: 39 000 so'm",
    "Donar-box tovuq go'shtli" : "Oq kunjut sousi ostidagi shirali grill tovuq go'shti, qarsildoq kartoshka-fri bilan guruch donalaridan tashkil topgan qatlamlarning to'yimli uyg'unlashuvi. Qulay, ixcham va to'yimli qadoq!\nNarxi: 37 000 so'm",
    "Strips" : "Qarsildoq panirovkadagi shirali, yumshoq tovuq go'shti\nNarxi: 21 000 so'm",
    "Sezar salat" : "Maxsus «Sezar» sousi ostida Aysberg  salati bargi, klyarda qovurilgan tovuq  bo'lakchalari, barra pomidorlar, pishloq  va sarimsoqli qarsildoq suxariklar\nNarxi: 25 000 so'm",
    "Sezar sous" : "Sezar salat uchun sous\nNarxi: 4 000 so'm",
    "Grecheskiy sous" : "Grecheskiy salat uchun sous\nNarxi: 4 000 so'm",
    "Pishloqli sous" : "Quyuq va ishtahaochar pishloqli sous portsiyasi. Sof og'irligi - 25 gr\nNarxi: 4 000 so'm",
    "Sarimsoqli sous" : "Shirin iforga ega sarimsoqli sous portsiyasi. Sof og'irligi - 25 gr\nNarxi: 4 000 so'm",
    "Ketchup" : "Tabiiy, yangi pomidorlar va ziravorlardan tayyorlangan ketchup portsiyasi. Sof og'irligi - 25 gr\nNarxi: 4 000 so'm",
    "Chili sous" : "Yengil-achchiq 'Chili' sousi portsiyasi. Sof og'irligi - 25 gr\nNarxi: 4 000 so'm",
    "Barbekyu sousi": "Tutunli karamellangan pomidor sous porsiyasi. Sof og'irligi - 25 g\nNarxi: 4 000 so'm",
    "Mayonez": "Klassik mayonez porsiyasi. Sof og'irligi - 25 gr\nNarxi: 4 000 so'm",
    "Mol go'shtidan donar" : "Kombinatsiyali idishda shirali gril mol go'shti bo'lakchalari, tillarang kartoshka-fri, miks-guruch, tabiiy, o'zimizda tayyorlangan salat, maxsus sous va shirin iforga ega kulcha non\nNarxi: 48 000 so'm",
    "Karameli donut" : "Karamelli glazurdagi yumshoq, mayin donatNarxi: 17 000 so'm",
    "Medovik (Asalli tort)" : "Smetanali krem bilan asalli, yumshoq biskvit\nNarxi: 19 000 so'm",
    "Chizkeyk" : "Pishloqli-qaymoqli krem bilan vanilli biskvit\nNarxi: 19 000 so'm",
    "Mevali Donut" : "Qulupnayli-yogurtli glazurdagi yumshoq, mayin donat\nNarxi: 17 000 so'm",
    "Kapuchino" : "Espresso asosidagi ko'pirtirilgan sut bilan tabiiy donador qahva.\nNarxi: 14 000 so'm",
    "Kofe Glyase" : "Donli amerikano issiq qahvasi bilan qaymoqli sovituvchi muzqaymoq\nNarxi: 14 000 so'm",
    "Limonli qora choy" : "Yangi limon bilan katta bargli, qora seylon choyi\nNarxi: 6 000 so'm",
    "Kofe Latte" : "Sut, espresso va ko'pirtirilgan sutdan iborat, uch qatlamli tabiiy donador qahva.\nNarxi: 14 000 so'm",
    "Amerikano" : "Tetiklashtiruvchi klassik donador qahva.\nNarxi: 12 000 so'm",
    "Ko’k choy" : "Katta bargli, ko'k seylon choyi\nNarxi: 5 000 so'm",
    "Qora choy" : "Katta bargli, qora seylon choyi\nNarxi: 5 000 so'm",
    "Limonli ko’k choy" : "Yangi limon bilan katta bargli, ko'k seylon choyi\nNarxi: 6 000 so'm",
    "Moxito" : "Moxito - xushbo'y laym sharbati, muzdek  gazlangan suv va yangi uzilgan limon bo'laklari  solingan salqinlik bag'ishlovchi limonad. Issiq  kun uchun salqinlovchi sitrus formulasi!\nNarxi: 15 000 so'm",
    "Pina colada" : "Pina colada - kokos bo'lakchalari, ananas  sharbati va muzdek gazlangan suvdan  tayyorlangan tetiklantiruvchi limonad. Ekzotik  tetiklik!\nNarxi: 15 000 so'm",
    "7up razliv" : "Shaxsiy qog'oz stakandagi quyma 7up 0,4l\nNarxi: 9 000 so'm",
    "Gazlangan suv 0.5L" : "“Chortoq” tozalangan gazli ichimlik suvi, 0,5 L\nNarxi: 5 000 so'm",
    "Olchali sharbat, 1 L" : "Olchali sharbat, 1 litr\nNarxi: 19 000 so'm",
    "Apelsinli sharbat, 1 L" : "Apelsinli sharbat, 1 litr\nNarxi: 19 000 so'm",
    "Mirinda razliv" : "Shaxsiy qog'oz stakandagi quyma Mirinda 0,4l\nNarxi: 9 000 so'm",
    "Pepsi 1,5L" : "Pepsi 1,5L\nNarxi: 20 000 so'm",
    "Pepsi razliv" : "Pepsi razliv\nNarxi: 9 000 so'm",
    "Olmali sharbat shakarsiz, 0,33L" : "Olmali sharbat shakarsiz, 0,33L\nNarxi: 10 000 so'm",
    "Pepsi 0,5L" : "Pepsi 0,5L\nNarxi: 11 000 so'm",
    "Talaba-Combo" : "Oson va tezkor, asosiysi tejamkor taomlanish uchun ideal variant! Stud-kombo tarkibiga mini Xot-Dog, kartoshka fri mini, firma stakanidagi Pepsi 0,4 L kiradi\nNarxi: 19 000 so'm",
    "S-Combo №1" : "S seriyadagi kombo tezkor, manfaatli va turli xil yeguliklar bilan taomlanishni istaydigan xaridorlar uchun mos keladi. Ushbu seriya takliflari tarkibiga eng mashhur taomlarning mini-versiyalari kiradi. S-kombo №1 tarkibiga kiradi: mol go'shtli lavash\nNarxi: 33 000 so'm",
    "S-Combo №2" : "S seriyadagi kombo tezkor, manfaatli va turli xil yeguliklar bilan taomlanishni istaydigan xaridorlar uchun mos keladi. Ushbu seriya takliflari tarkibiga eng mashhur taomlarning mini-versiyalari kiradi. S-kombo №2 tarkibiga kiradi: tovuq go'shtli lavash mini, bir porsiya tilla rangli kartoshka fri mini va bir stakan 'Pepsi'\nNarxi: 33 000 so'm",
    "S-Combo №3" : "S seriyadagi kombo tezkor, manfaatli va turli xil yeguliklar bilan taomlanishni istaydigan xaridorlar uchun mos keladi. Ushbu seriya takliflari tarkibiga eng mashhur taomlarning mini-versiyalari kiradi. S-kombo №3 tarkibiga kiradi: mol go'shtli mini shaurma, bir porsiya tilla rangli kartoshka fri mini va bir stakan 'Pepsi'\nNarxi: 33 000 so'm",
    "S-Combo №4" : "S seriyadagi kombo tezkor, manfaatli va turli xil yeguliklar bilan taomlanishni istaydigan xaridorlar uchun mos keladi. Ushbu seriya takliflari tarkibiga eng mashhur taomlarning mini-versiyalari kiradi. S-kombo №4 tarkibiga kiradi: tovuq go'shtli mini shaurma, bir porsiya tilla rangli kartoshka fri mini va bir stakan 'Pepsi'\nNarxi: 33 000 so'm",
    "M-Combo 2" : "M seriyadagi taklif - Kombo to'laqonli taomlanishni istaydigan xaridorlar uchun mos keladi. Ushbu seriya tarkibiga kompleks taom, snek va ichimlik kiradi. M - Kombo №2 tarkibiga kiradi: mo'l go'shtli shaurma, kartoshka fri va bir stakan 'Pepsi'\nNarxi: 43 000 so'm",
    "Bolalar uchun Combo" : "Bolalar uchun mo'ljallangan mazali xot-dog, bolalar uchun mo'ljallangan, tabiiy 'Bliss Smile' sharbati (200 ml) va tillarang kartoshka-fri portsiyasi\nNarxi: 19 000 so'm",
    "M-Combo 3" : "M seriyadagi taklif - Kombo to'laqonli taomlanishni isyaydigan xaridorlar uchun mos keladi. Ushbu seriya tarkibiga kompleks taom, snek va ichimlik kiradi. M - Kombo №3 tarkibiga kiradi: Mol go'shtli Trindwich, kartoshka fri va bir stakan 'Pepsi'\nNarxi: 47 000 so'm",
    "M-Combo 1" : "M seriyadagi taklif - Kombo to'laqonli taomlanishni istaydigan xaridorlar uchun mos keladi. Ushbu seriya tarkibiga kompleks taom, snek va ichimlik kiradi. M - Kombo №1 tarkibiga kiradi: Mol go'shtli lavash, kartoshka fri va bir stakan 'Pepsi'\nNarxi: 45 000 so'm",
    "M-Combo 4" : "M seriyadagi taklif - Kombo to'laqonli taomlanishni isyaydigan xaridorlar uchun mos keladi. Ushbu seriya tarkibiga kompleks taom, snek va ichimlik kiradi. M - Kombo №4 tarkibiga kiradi: Chizburger, kartoshka fri va bir stakan 'Pepsi'\nNarxi: 40 000 so'm",
    "M-Combo 5" : "M seriyadagi taklif - Kombo to'laqonli taomlanishni isyaydigan xaridorlar uchun mos keladi. Ushbu seriya tarkibiga kompleks taom, snek va ichimlik kiradi. M - Kombo №5 tarkibiga kiradi: Xot-dog, kartoshka fri va bir stakan 'Pepsi'\nNarxi: 31 000 so'm",
}
